// ANSI rendering primitives + HTML export for the Agentic OS dashboard.
// Single source of truth: everything is built as an ANSI string, then either
// printed to a TTY, stripped for pipes, or converted to HTML.

const SGR = (code) => (s) => `\x1b[${code}m${s}\x1b[0m`;

export const c = {
  bold: SGR(1),
  dim: SGR(2),
  red: SGR(31),
  green: SGR(32),
  yellow: SGR(33),
  cyan: SGR(36),
  gray: SGR(90),
};

export const glyph = {
  ok: '✓',
  fail: '✗',
  pending: '◷',
  wip: '▸',
  next: '○',
  done: '✓',
  refresh: '⟳',
  warn: '⚠',
  ready: '✅',
};

export function stripAnsi(s) {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: matching ANSI SGR codes is the point.
  return s.replace(/\x1b\[[0-9;]*m/g, '');
}

export function visibleLen(s) {
  return [...stripAnsi(s)].length;
}

export function termWidth() {
  return Math.max(72, Math.min(process.stdout.columns || 100, 100));
}

export function rule(ch = '═', width = termWidth()) {
  return c.gray(ch.repeat(width));
}

export function sectionBar(title, width = termWidth()) {
  const label = `══ ${title} `;
  const fill = Math.max(0, width - visibleLen(label));
  return c.cyan(c.bold(label) + '═'.repeat(fill));
}

// Left text + right text on one line, padded to width.
export function spread(left, right, width = termWidth()) {
  const pad = Math.max(1, width - visibleLen(left) - visibleLen(right));
  return left + ' '.repeat(pad) + right;
}

// Pad a label column so values align.
export function label(text, w = 8) {
  const pad = Math.max(0, w - visibleLen(text));
  return c.gray(text) + ' '.repeat(pad);
}

// Right-pad to a target *visible* width (ANSI-aware, unlike String.padEnd).
export function padV(s, w) {
  return s + ' '.repeat(Math.max(0, w - visibleLen(s)));
}

// Convert the limited SGR codes we emit into inline-styled HTML spans.
function ansiToHtml(s) {
  const map = {
    1: 'font-weight:700',
    2: 'opacity:.55',
    31: 'color:#ff5f56',
    32: 'color:#3ddc84',
    33: 'color:#e5c07b',
    36: 'color:#56b6c2',
    90: 'color:#7f848e',
  };
  // biome-ignore lint/suspicious/noControlCharactersInRegex: parsing ANSI SGR codes.
  const re = /\x1b\[([0-9;]*)m/g;
  const esc = (t) =>
    t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  let out = '';
  let idx = 0;
  let active = [];
  let m;
  const emit = (t) => {
    if (!t) return;
    const style = active
      .map((code) => map[code])
      .filter(Boolean)
      .join(';');
    out += style ? `<span style="${style}">${esc(t)}</span>` : esc(t);
  };
  // biome-ignore lint/suspicious/noAssignInExpressions: standard regex exec loop.
  while ((m = re.exec(s))) {
    emit(s.slice(idx, m.index));
    idx = re.lastIndex;
    const codes = m[1] === '' ? ['0'] : m[1].split(';');
    for (const code of codes) {
      if (code === '0') active = [];
      else active.push(Number(code));
    }
  }
  emit(s.slice(idx));
  return out;
}

export function renderHtml(ansi, refreshedAt) {
  const body = ansiToHtml(ansi);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FundedEdge · Agentic OS</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; background:#0b0e14; color:#c5ccd6;
    font:13px/1.45 ui-monospace,SFMono-Regular,"JetBrains Mono",Menlo,Consolas,monospace; }
  .wrap { max-width:1000px; margin:0 auto; padding:24px 18px 60px; }
  .bar { display:flex; align-items:center; gap:10px; margin-bottom:14px; }
  .dot { width:11px; height:11px; border-radius:50%; }
  .r{background:#ff5f56}.y{background:#ffbd2e}.g{background:#27c93f}
  h1 { font-size:13px; letter-spacing:.18em; color:#7f848e; margin:0; font-weight:600; }
  pre { white-space:pre-wrap; word-break:break-word; margin:0;
    background:#0f131c; border:1px solid #1c2230; border-radius:10px;
    padding:18px 20px; box-shadow:0 1px 0 #1c2230 inset; }
  footer { margin-top:16px; color:#5a6068; font-size:11px; }
</style></head>
<body><div class="wrap">
  <div class="bar"><span class="dot r"></span><span class="dot y"></span><span class="dot g"></span>
    <h1>FUNDEDEDGE · AGENTIC OS</h1></div>
  <pre>${body}</pre>
  <footer>Generated by <code>pnpm agenticos status --html</code> · ${esc(refreshedAt)}</footer>
</div></body></html>`;
}

function esc(t) {
  return String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Print to stdout: full color on a TTY, stripped otherwise (pipes/files).
export function print(ansi) {
  const useColor = process.stdout.isTTY && !process.env.NO_COLOR;
  process.stdout.write((useColor ? ansi : stripAnsi(ansi)) + '\n');
}
